apiVersion: kubeflow.org/v1beta1
kind: Experiment
metadata:
  namespace: josephadmin 
  labels:
    controller-tools.k8s.io: '1.0'
  name: experiment-one
spec: 
  parallelTrialCount: 3
  maxTrialCount: 12
  maxFailedTrialCount: 3 
  objective: 
    type: maximize
    goal: 0.99
    objectiveMetricName: accuracy
    additionalMetricNames:
  metricsCollectorSpec: 
    collector:
      kind: StdOut
  algorithms:
    algorithmName: random 
  parameters:
    - name: learning_rate
      parameterType: double
      feasibleSpace:
        list:
        min: 0.001
        max: 0.01
    - name: optimizer
      parameterType: categorical
      feasibleSpace:
        list:
          - sgd
          - adam
  trialTemplate:
    primaryContainerName: tensorflow
    trialParameters:
      - name: learningRate
        description: Learning rate for the training model
        reference: learning_rate
      - name: optimizer
        description: Training model optimizer (sdg, adam)
        reference: optimizer
    trialSpec:
      apiVersion: batch/v1
      kind: TFJob
      spec:
        template:
	  metadata:
            annotations:
              sidecar.istio.io/inject: "false"
          spec:
            containers:
              - name: tensorflow
                image: josephcruisedocker8624/tfjob:6.0
                command:
                  - "python3"
                  - "/tfjob.py"
                  - "--saved_model_dir=/train/saved_model/"
                  - "--learning_rate=${trialParameters.learningRate}"
                  - "--optimizer=${trialParameters.optimizer}"
            restartPolicy: Never